import { Link } from 'react-router-dom'
import SEOHead from '../components/SEOHead'

const stories = [
  { client: 'Kuber Shree Jewellers', sector: 'Premium jewellery', brief: 'Create a stronger premium presence across customer-facing marketing.', work: 'Marketing direction, campaign execution, and a more consistent visual presentation.', outcome: 'Client reported that the work upgraded how the brand looks and feels to customers.' },
  { client: 'Symphony', sector: 'Cafe and restaurant', brief: 'Translate the cafe’s specific atmosphere into a marketing system.', work: 'Brand-aligned creative direction and social media strategy shaped around the venue’s character.', outcome: 'Client reported a genuine shift in customer engagement.' },
  { client: 'The Studio 11', sector: 'Premium salon · Indore', brief: 'Turn an inactive social presence into a useful local acquisition channel.', work: 'Aesthetic direction, local positioning, and consistent social content.', outcome: 'Client reported stronger local presence and regular high-value client enquiries.' },
]

export default function CaseStudies() {
  const schema = stories.map(s => ({ '@context': 'https://schema.org', '@type': 'Article', headline: `${s.client} marketing case study`, about: s.sector, author: { '@type': 'Organization', name: 'thenightera' }, publisher: { '@type': 'Organization', name: 'thenightera' }, description: `${s.brief} ${s.outcome}` }))
  return <main className="min-h-screen bg-white text-[#1d1d1f]"><SEOHead title="Marketing Case Studies" description="Selected thenightera client stories across jewellery, hospitality, and beauty. See each brief, delivered work, and client-reported outcome." path="/case-studies" schema={schema} />
    <section className="mx-auto max-w-6xl px-6 pb-20 pt-28 md:px-10 md:pb-28 md:pt-36"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#7D2027]">Selected client stories</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[0.96] tracking-[-0.055em] sm:text-6xl md:text-8xl">Work, explained clearly.</h1><p className="speakable mt-8 max-w-3xl text-lg leading-8 text-[#5f5f63]">These case studies show the business brief, work thenightera delivered, and outcome reported by each client. We publish qualitative results when verified numeric data is unavailable.</p></section>
    <section className="border-t border-black/10 bg-[#FAF7F2]"><div className="mx-auto max-w-6xl px-6 py-20 md:px-10 md:py-28">{stories.map((s, i) => <article key={s.client} className="grid gap-8 border-b border-black/10 py-12 first:pt-0 md:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-semibold text-[#A39670]">0{i + 1} · {s.sector}</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.035em]">{s.client}</h2></div><div className="grid gap-6 sm:grid-cols-3"><div><h3 className="text-sm font-semibold">Brief</h3><p className="mt-2 leading-7 text-[#5f5f63]">{s.brief}</p></div><div><h3 className="text-sm font-semibold">Work</h3><p className="mt-2 leading-7 text-[#5f5f63]">{s.work}</p></div><div><h3 className="text-sm font-semibold">Reported outcome</h3><p className="mt-2 leading-7 text-[#5f5f63]">{s.outcome}</p></div></div></article>)}<div className="mt-14 rounded-[32px] bg-[#1d1d1f] p-8 text-white md:p-12"><h2 className="text-4xl font-semibold tracking-[-0.045em]">Build next story with us.</h2><Link to="/contact" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#1d1d1f] no-underline">Start a conversation</Link></div></div></section>
  </main>
}
